import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { runInit } from '../../src/cli/commands/init';
import { detectProject } from '../../src/cli/detect';
import type { CliIO } from '../../src/cli/types';

interface TestIO extends CliIO {
  stdout: string[];
  stderr: string[];
}

function makeIO(opts?: {
  interactive?: boolean;
  stdoutTTY?: boolean;
  confirms?: boolean[];
  prompts?: string[];
}): TestIO {
  const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'grafeo-init-'));
  const stdout: string[] = [];
  const stderr: string[] = [];
  const confirms = [...(opts?.confirms ?? [])];
  const prompts = [...(opts?.prompts ?? [])];
  return {
    cwd,
    env: {},
    out: (l) => stdout.push(l),
    err: (l) => stderr.push(l),
    interactive: opts?.interactive,
    stdoutTTY: opts?.stdoutTTY,
    confirm: async () => confirms.shift() ?? false,
    prompt: async (_q, def) => prompts.shift() ?? def ?? '',
    stdout,
    stderr,
  };
}

const read = (cwd: string, f: string) =>
  fs.readFileSync(path.join(cwd, f), 'utf-8');

const GENERATED_FILE =
  '// AUTO-GENERATED FILE\n// Generated by grafeo-ogm generateTypes()\nexport type X = 1;\n';

describe('detectProject', () => {
  it('finds grafeo schemas by directive and generated files by marker', () => {
    const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'grafeo-detect-'));
    fs.writeFileSync(
      path.join(cwd, 'schema.graphql'),
      'type Movie @node { title: String! @unique }\n',
    );
    // A bare GraphQL file WITHOUT grafeo directives must be ignored.
    fs.writeFileSync(
      path.join(cwd, 'other.graphql'),
      'type Query { hello: String }\n',
    );
    fs.mkdirSync(path.join(cwd, 'src'));
    fs.writeFileSync(path.join(cwd, 'src', 'ogm-types.ts'), GENERATED_FILE);

    const d = detectProject(cwd, {});
    expect(d.schemaCandidates).toEqual(['schema.graphql']);
    expect(d.generatedTypes).toBe(path.join('src', 'ogm-types.ts'));
  });

  it('reports nothing in an empty project', () => {
    const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'grafeo-detect-'));
    const d = detectProject(cwd, {});
    expect(d.schemaCandidates).toEqual([]);
    expect(d.generatedTypes).toBeUndefined();
    expect(d.existingConfig).toBeUndefined();
  });

  it('does not misdetect a file that merely mentions the marker in prose', () => {
    const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'grafeo-detect-'));
    fs.writeFileSync(
      path.join(cwd, 'notes.ts'),
      '// This file is NOT Generated by grafeo-ogm generateTypes()\nexport const x = 1;\n',
    );
    const d = detectProject(cwd, {});
    expect(d.generatedTypes).toBeUndefined();
  });
});

describe('grafeo init (cli-init spec)', () => {
  it('greenfield: scaffolds the movie schema + config and points at generate', async () => {
    const io = makeIO();
    const code = await runInit([], io);

    expect(code).toBe(0);
    expect(read(io.cwd, 'grafeo.config.ts')).toContain(
      'schema: "./schema.graphql"',
    );
    const schema = read(io.cwd, 'schema.graphql');
    expect(schema).toContain('type Movie @node');
    expect(schema).toContain('ACTED_IN');
    expect(io.stdout.join('\n')).toContain('grafeo generate');
  });

  it('autodetects an existing schema + generated types and wires the config to them', async () => {
    const io = makeIO();
    fs.writeFileSync(
      path.join(io.cwd, 'schema.graphql'),
      'type Movie @node { title: String! @unique }\n',
    );
    fs.mkdirSync(path.join(io.cwd, 'src'));
    fs.writeFileSync(path.join(io.cwd, 'src', 'ogm-types.ts'), GENERATED_FILE);

    const code = await runInit([], io);

    expect(code).toBe(0);
    const config = read(io.cwd, 'grafeo.config.ts');
    expect(config).toContain('schema: "./schema.graphql"');
    expect(config).toContain('out: "./src/ogm-types.ts"');
    // The existing schema is left untouched, not overwritten with the movie example.
    expect(read(io.cwd, 'schema.graphql')).not.toContain('Person');
  });

  it('prompts to choose among multiple schema candidates', async () => {
    const io = makeIO({ interactive: true, confirms: [true], prompts: ['2'] });
    fs.writeFileSync(
      path.join(io.cwd, 'a.graphql'),
      'type Movie @node { title: String! @unique }\n',
    );
    fs.writeFileSync(
      path.join(io.cwd, 'b.graphql'),
      'type Person @node { name: String! @id @unique }\n',
    );

    const code = await runInit([], io);

    expect(code).toBe(0);
    // Sorted alphabetically (neither is named schema.graphql); "2" picks b.
    expect(read(io.cwd, 'grafeo.config.ts')).toContain('schema: "./b.graphql"');
  });

  it('--fresh ignores a detected setup and scaffolds the movie schema', async () => {
    const io = makeIO();
    fs.writeFileSync(
      path.join(io.cwd, 'existing.graphql'),
      'type Movie @node { title: String! @unique }\n',
    );

    const code = await runInit(['--fresh'], io);

    expect(code).toBe(0);
    expect(read(io.cwd, 'grafeo.config.ts')).toContain(
      'schema: "./schema.graphql"',
    );
    expect(read(io.cwd, 'schema.graphql')).toContain('type Movie @node');
  });

  it('refuses to overwrite an existing config without --force (non-interactive)', async () => {
    const io = makeIO();
    fs.writeFileSync(
      path.join(io.cwd, 'grafeo.config.ts'),
      'export default {};\n',
    );

    await expect(runInit([], io)).rejects.toThrow(/--force/);
    // Untouched.
    expect(read(io.cwd, 'grafeo.config.ts')).toBe('export default {};\n');
  });

  it('overwrites an existing config with --force', async () => {
    const io = makeIO();
    fs.writeFileSync(
      path.join(io.cwd, 'grafeo.config.ts'),
      'export default {};\n',
    );

    const code = await runInit(['--force'], io);

    expect(code).toBe(0);
    expect(read(io.cwd, 'grafeo.config.ts')).toContain('defineConfig');
  });

  it('adds a "generate" npm script and preserves the rest', async () => {
    const io = makeIO();
    fs.writeFileSync(
      path.join(io.cwd, 'package.json'),
      JSON.stringify({ name: 'x', scripts: { test: 'jest' } }, null, 2),
    );

    await runInit([], io);

    const pkg = JSON.parse(read(io.cwd, 'package.json')) as {
      scripts: Record<string, string>;
    };
    expect(pkg.scripts.generate).toBe('grafeo generate');
    expect(pkg.scripts.test).toBe('jest');
    expect(io.stdout.join('\n')).toContain('generate');
  });

  it('preserves an existing "generate" script', async () => {
    const io = makeIO();
    fs.writeFileSync(
      path.join(io.cwd, 'package.json'),
      JSON.stringify({ scripts: { generate: 'custom-thing' } }, null, 2),
    );

    await runInit([], io);

    const pkg = JSON.parse(read(io.cwd, 'package.json')) as {
      scripts: Record<string, string>;
    };
    expect(pkg.scripts.generate).toBe('custom-thing');
  });

  it('--seed scaffolds an upsert stub and wires it into the config', async () => {
    const io = makeIO();
    const code = await runInit(['--seed'], io);

    expect(code).toBe(0);
    expect(read(io.cwd, 'seed.ts')).toContain('upsert');
    expect(read(io.cwd, 'grafeo.config.ts')).toContain("seed: './seed.ts'");
  });

  it('writes an env-based connection and never prompts for secrets', async () => {
    const io = makeIO({ interactive: true });
    const code = await runInit(['--yes'], io);

    expect(code).toBe(0);
    const config = read(io.cwd, 'grafeo.config.ts');
    expect(config).toContain('process.env.NEO4J_URI');
    expect(config).toContain('process.env.NEO4J_PASSWORD');
  });

  it('safely escapes a path containing a quote — no config injection', async () => {
    const io = makeIO();
    // Interpolated raw, this path would close the string literal and inject
    // code into the jiti-executed config. JSON.stringify must neutralize it.
    const evil = "x'+require('node:fs')+'";
    await runInit(['--schema', `${evil}.graphql`], io);

    const config = read(io.cwd, 'grafeo.config.ts');
    // Emitted as a fully-escaped JSON string literal…
    expect(config).toContain(`schema: ${JSON.stringify(`./${evil}.graphql`)}`);
    // …never as the raw single-quoted break-out form.
    expect(config).not.toContain(`schema: './${evil}.graphql'`);
  });

  it('shows the logo splash when stdout is a TTY', async () => {
    const io = makeIO({ interactive: true, stdoutTTY: true });
    await runInit([], io);
    expect(io.stdout.join('\n')).toContain('type-safe ogm for neo4j');
  });

  it('omits the splash when stdout is redirected (no captured-output noise)', async () => {
    // interactive stdin but stdout piped to a file — the splash must NOT leak.
    const io = makeIO({ interactive: true, stdoutTTY: false });
    await runInit([], io);
    expect(io.stdout.join('\n')).not.toContain('type-safe ogm for neo4j');
  });
});
