import * as fs from 'node:fs';
import * as path from 'node:path';

/** What `grafeo init` found (or didn't) in an existing project. */
export interface DetectionResult {
  /** `.graphql`/`.gql` files that carry grafeo directives (relative to cwd). */
  schemaCandidates: string[];
  /** A previously generated types file, identified by the header marker. */
  generatedTypes?: string;
  /** An existing grafeo.config.{ts,js,json}, if present. */
  existingConfig?: string;
  /** True if a NEO4J_* env var or a .env mentioning one is present. */
  hasNeo4jEnv: boolean;
}

// Directories never worth scanning — large, generated, or VCS internals.
const SKIP_DIRS = new Set([
  'node_modules',
  'dist',
  'build',
  '.git',
  '.next',
  'coverage',
  '.turbo',
]);
const MAX_DEPTH = 3;
const CONFIG_NAMES = [
  'grafeo.config.ts',
  'grafeo.config.js',
  'grafeo.config.json',
];
// Generated files open with a `// Generated by <pkg> generateTypes()` header
// line (utility-types emitter). Anchor to the line start so a doc comment that
// merely mentions the phrase isn't misdetected, and allow any package name so
// files generated under an npm alias still match.
const GENERATED_MARKER = /^\/\/\s*Generated by .+ generateTypes\(\)/m;
// A schema is grafeo's only if it actually uses grafeo's directives — a bare
// GraphQL file in the tree must not be mistaken for the OGM schema.
const GRAFEO_DIRECTIVE = /@(node|relationship|relationshipProperties)\b/;

function walk(root: string, depth: number, out: string[]): void {
  let entries: fs.Dirent[];
  try {
    entries = fs.readdirSync(root, { withFileTypes: true });
  } catch {
    return;
  }
  for (const entry of entries) {
    if (entry.name.startsWith('.') && entry.name !== '.env') continue;
    const full = path.join(root, entry.name);
    if (entry.isDirectory()) {
      if (depth >= MAX_DEPTH || SKIP_DIRS.has(entry.name)) continue;
      walk(full, depth + 1, out);
    } else if (entry.isFile()) out.push(full);
  }
}

function readHead(file: string, bytes = 4096): string {
  try {
    const fd = fs.openSync(file, 'r');
    try {
      const buf = Buffer.alloc(bytes);
      const read = fs.readSync(fd, buf, 0, bytes, 0);
      return buf.toString('utf-8', 0, read);
    } finally {
      fs.closeSync(fd);
    }
  } catch {
    return '';
  }
}

/**
 * Scan `cwd` for an existing grafeo setup so `init` can wire itself up. Pure
 * filesystem reads — shallow, with generated/VCS dirs skipped — so it stays
 * fast and never walks `node_modules`.
 */
export function detectProject(
  cwd: string,
  env: NodeJS.ProcessEnv,
): DetectionResult {
  const files: string[] = [];
  walk(cwd, 0, files);

  const schemaCandidates: string[] = [];
  let generatedTypes: string | undefined;

  for (const file of files) {
    const ext = path.extname(file);
    const rel = path.relative(cwd, file);
    if (ext === '.graphql' || ext === '.gql') {
      // Only count it as the schema if it actually uses grafeo directives.
      // Head-read (guarded + capped) like the .ts sniff — directives sit at the
      // top of real schemas, and this avoids reading (or throwing on) a huge or
      // unreadable file.
      if (GRAFEO_DIRECTIVE.test(readHead(file, 65536)))
        schemaCandidates.push(rel);
    } else if (ext === '.ts' && !generatedTypes)
      if (GENERATED_MARKER.test(readHead(file))) generatedTypes = rel;
  }

  // Prefer a file literally named schema.graphql when several candidates exist.
  schemaCandidates.sort((a, b) => {
    const an = path.basename(a) === 'schema.graphql' ? 0 : 1;
    const bn = path.basename(b) === 'schema.graphql' ? 0 : 1;
    return an - bn || a.localeCompare(b);
  });

  let existingConfig: string | undefined;
  for (const name of CONFIG_NAMES)
    if (fs.existsSync(path.join(cwd, name))) {
      existingConfig = name;
      break;
    }

  const hasNeo4jEnv =
    Object.keys(env).some((k) => k.startsWith('NEO4J_')) ||
    (fs.existsSync(path.join(cwd, '.env')) &&
      /^\s*NEO4J_/m.test(readHead(path.join(cwd, '.env'))));

  return { schemaCandidates, generatedTypes, existingConfig, hasNeo4jEnv };
}
