/**
 * Emits the static utility types that appear at the top of every generated
 * `ogm-types.ts` file.  These types are schema-independent.
 */

// ---------------------------------------------------------------------------
// Header
// ---------------------------------------------------------------------------

export function emitHeader(
  config?: { header?: string },
  packageName = 'grafeo-ogm',
): string {
  const lines = [
    '// AUTO-GENERATED FILE — DO NOT EDIT',
    `// Generated by ${packageName} generateTypes()`,
  ];

  if (config?.header) lines.push(config.header);

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Imports
// ---------------------------------------------------------------------------

export function emitImports(packageName = 'grafeo-ogm'): string {
  return [
    'import type { SelectionSetNode, DocumentNode } from "graphql";',
    `import type { ModelInterface, InterfaceModelInterface, ExecutionContext } from "${packageName}";`,
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Utility types (copied verbatim from the Neo4j OGM codegen output)
// ---------------------------------------------------------------------------

export function emitUtilityTypes(): string {
  return `export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = {
  [K in keyof T]: T[K];
};
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & {
  [SubKey in K]?: Maybe<T[SubKey]>;
};
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & {
  [SubKey in K]: Maybe<T[SubKey]>;
};
export type MakeEmpty<
  T extends { [key: string]: unknown },
  K extends keyof T
> = { [_ in K]?: never };
export type Incremental<T> =
  | T
  | {
      [P in keyof T]?: P extends " $fragmentName" | "__typename" ? T[P] : never;
    };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  /** The \`ID\` scalar type represents a unique identifier, often used to refetch an object or as key for a cache. The ID type appears in a JSON response as a String; however, it is not intended to be human-readable. When expected as an input type, any string (such as \`"4"\`) or integer (such as \`4\`) input value will be accepted as an ID. */
  ID: { input: string; output: string };
  /** The \`String\` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text. */
  String: { input: string; output: string };
  /** The \`Boolean\` scalar type represents \`true\` or \`false\`. */
  Boolean: { input: boolean; output: boolean };
  /** The \`Int\` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^31) and 2^31 - 1. */
  Int: { input: number; output: number };
  /** The \`Float\` scalar type represents signed double-precision fractional values as specified by [IEEE 754](https://en.wikipedia.org/wiki/IEEE_floating_point). */
  Float: { input: number; output: number };
  /** A date and time, represented as an ISO-8601 string */
  DateTime: { input: any; output: any };
  /** A 64-bit integer, represented as a string to avoid precision loss */
  BigInt: { input: string; output: string };
  /** A date without time, represented as an ISO-8601 date string (e.g. "2024-01-15") */
  Date: { input: string; output: string };
  /** A time with UTC offset, represented as an ISO-8601 time string (e.g. "12:30:00Z") */
  Time: { input: string; output: string };
  /** A local time without timezone, represented as an ISO-8601 time string (e.g. "12:30:00") */
  LocalTime: { input: string; output: string };
  /** A local date and time without timezone, represented as an ISO-8601 string */
  LocalDateTime: { input: string; output: string };
  /** An ISO 8601 duration (e.g. "P1Y2M3DT4H5M6S") */
  Duration: { input: string; output: string };
  /** A geographic point (WGS 84). Input accepts latitude/longitude; output uses x (longitude), y (latitude) from the driver */
  Point: {
    input: { latitude: number; longitude: number; height?: number; srid?: number };
    output: { x: number; y: number; z?: number; srid: number };
  };
  /** A cartesian point with x, y, optional z coordinates, and SRID */
  CartesianPoint: {
    input: { x: number; y: number; z?: number; srid?: number };
    output: { x: number; y: number; z?: number; srid: number };
  };
};`;
}
