/**
 * 13 - Code Generation
 *
 * Demonstrates generateTypes() to produce TypeScript types from a schema.
 * This example does NOT require a running Neo4j instance.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { generateTypes } from 'grafeo-ogm';

async function main() {
  const typeDefs = fs.readFileSync(
    path.join(__dirname, 'schema.graphql'),
    'utf-8',
  );

  const outFile = path.join(__dirname, 'generated-types.ts');

  // --- Basic generation ---
  const result = await generateTypes({
    typeDefs,
    outFile,
  });

  console.log('Output path:', result.outputPath);
  console.log('Type count:', result.typeCount);
  console.log('File size:', result.fileSize, 'bytes');
  console.log('Duration:', result.durationMs, 'ms');

  if (result.warnings.length > 0) {
    console.log('Warnings:');
    for (const w of result.warnings) {
      console.log(`  [${w.code}] ${w.message}`, w.location ?? '');
    }
  }

  // Preview the generated file
  const content = fs.readFileSync(outFile, 'utf-8');
  console.log('\n--- Generated file preview (first 50 lines) ---');
  console.log(content.split('\n').slice(0, 50).join('\n'));

  // --- Generation with custom config ---
  const customResult = await generateTypes({
    typeDefs,
    outFile: path.join(__dirname, 'generated-types-custom.ts'),
    config: {
      stringMatchesFilter: false,
      formatOutput: true,
      header: '// Auto-generated by grafeo-ogm — do not edit',
      packageName: 'grafeo-ogm',
    },
  });
  console.log('\nCustom generation:', customResult.typeCount, 'types');

  // Clean up generated files
  fs.unlinkSync(outFile);
  fs.unlinkSync(path.join(__dirname, 'generated-types-custom.ts'));
  console.log('\nCleaned up generated files');
}

main().catch(console.error);
