// AUTO-GENERATED FILE — DO NOT EDIT
// Generated by grafeo-ogm generateTypes()

import type { SelectionSetNode, DocumentNode } from "graphql";
import type {
  ModelInterface,
  InterfaceModelInterface,
  ExecutionContext,
} from "grafeo-ogm";

export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = {
  [K in keyof T]: T[K];
};
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & {
  [SubKey in K]?: Maybe<T[SubKey]>;
};
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & {
  [SubKey in K]: Maybe<T[SubKey]>;
};
export type MakeEmpty<
  T extends { [key: string]: unknown },
  K extends keyof T,
> = { [_ in K]?: never };
export type Incremental<T> =
  | T
  | {
      [P in keyof T]?: P extends " $fragmentName" | "__typename" ? T[P] : never;
    };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  /** The `ID` scalar type represents a unique identifier, often used to refetch an object or as key for a cache. The ID type appears in a JSON response as a String; however, it is not intended to be human-readable. When expected as an input type, any string (such as `"4"`) or integer (such as `4`) input value will be accepted as an ID. */
  ID: { input: string; output: string };
  /** The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text. */
  String: { input: string; output: string };
  /** The `Boolean` scalar type represents `true` or `false`. */
  Boolean: { input: boolean; output: boolean };
  /** The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^31) and 2^31 - 1. */
  Int: { input: number; output: number };
  /** The `Float` scalar type represents signed double-precision fractional values as specified by [IEEE 754](https://en.wikipedia.org/wiki/IEEE_floating_point). */
  Float: { input: number; output: number };
  /** A date and time, represented as an ISO-8601 string */
  DateTime: { input: any; output: any };
  /** A 64-bit integer, represented as a string to avoid precision loss */
  BigInt: { input: string; output: string };
  /** A date without time, represented as an ISO-8601 date string (e.g. "2024-01-15") */
  Date: { input: string; output: string };
  /** A time with UTC offset, represented as an ISO-8601 time string (e.g. "12:30:00Z") */
  Time: { input: string; output: string };
  /** A local time without timezone, represented as an ISO-8601 time string (e.g. "12:30:00") */
  LocalTime: { input: string; output: string };
  /** A local date and time without timezone, represented as an ISO-8601 string */
  LocalDateTime: { input: string; output: string };
  /** An ISO 8601 duration (e.g. "P1Y2M3DT4H5M6S") */
  Duration: { input: string; output: string };
  /** A geographic point (WGS 84). Input accepts latitude/longitude; output uses x (longitude), y (latitude) from the driver */
  Point: {
    input: {
      latitude: number;
      longitude: number;
      height?: number;
      srid?: number;
    };
    output: { x: number; y: number; z?: number; srid: number };
  };
  /** A cartesian point with x, y, optional z coordinates, and SRID */
  CartesianPoint: {
    input: { x: number; y: number; z?: number; srid?: number };
    output: { x: number; y: number; z?: number; srid: number };
  };
};

export enum BookStatus {
  Draft = "DRAFT",
  Published = "PUBLISHED",
  Archived = "ARCHIVED",
}

export enum SortDirection {
  Asc = "ASC",
  Desc = "DESC",
}

export type Author = {
  __typename?: "Author";
  id: Scalars["ID"]["output"];
  name: Scalars["String"]["output"];
  bio?: Maybe<Scalars["String"]["output"]>;
  bornYear?: Maybe<Scalars["Int"]["output"]>;
  booksAggregate?: Maybe<AuthorBookBooksAggregationSelection>;
  books: Array<Book>;
  booksConnection: AuthorBooksConnection;
};

export type Book = {
  __typename?: "Book";
  id: Scalars["ID"]["output"];
  title: Scalars["String"]["output"];
  isbn?: Maybe<Scalars["String"]["output"]>;
  description?: Maybe<Scalars["String"]["output"]>;
  price?: Maybe<Scalars["Float"]["output"]>;
  published?: Maybe<Scalars["DateTime"]["output"]>;
  status?: Maybe<BookStatus>;
  authorAggregate?: Maybe<BookAuthorAuthorAggregationSelection>;
  author: Author;
  authorConnection: BookAuthorConnection;
  categoriesAggregate?: Maybe<BookCategoryCategoriesAggregationSelection>;
  categories: Array<Category>;
  categoriesConnection: BookCategoriesConnection;
  reviewsAggregate?: Maybe<BookReviewReviewsAggregationSelection>;
  reviews: Array<Review>;
  reviewsConnection: BookReviewsConnection;
};

export type Category = {
  __typename?: "Category";
  id: Scalars["ID"]["output"];
  name: Scalars["String"]["output"];
  booksAggregate?: Maybe<CategoryBookBooksAggregationSelection>;
  books: Array<Book>;
  booksConnection: CategoryBooksConnection;
};

export type Publisher = {
  __typename?: "Publisher";
  id: Scalars["ID"]["output"];
  name: Scalars["String"]["output"];
  website?: Maybe<Scalars["String"]["output"]>;
};

export type Review = {
  __typename?: "Review";
  id: Scalars["ID"]["output"];
  rating: Scalars["Int"]["output"];
  comment?: Maybe<Scalars["String"]["output"]>;
  bookAggregate?: Maybe<ReviewBookBookAggregationSelection>;
  book: Book;
  bookConnection: ReviewBookConnection;
};

export type InCategory = {
  addedAt?: Maybe<Scalars["DateTime"]["output"]>;
  isPrimary?: Maybe<Scalars["Boolean"]["output"]>;
};

export type WrittenBy = {
  role?: Maybe<Scalars["String"]["output"]>;
  year?: Maybe<Scalars["Int"]["output"]>;
};

export type Entity = {
  id: Scalars["ID"]["output"];
  name: Scalars["String"]["output"];
};

export enum EntityImplementation {
  Author = "Author",
  Publisher = "Publisher",
}

export type AuthorWhere = {
  id?: InputMaybe<Scalars["ID"]["input"]>;
  id_NOT?: InputMaybe<Scalars["ID"]["input"]>;
  id_IN?: InputMaybe<Array<Scalars["ID"]["input"]>>;
  id_NOT_IN?: InputMaybe<Array<Scalars["ID"]["input"]>>;
  id_CONTAINS?: InputMaybe<Scalars["ID"]["input"]>;
  id_STARTS_WITH?: InputMaybe<Scalars["ID"]["input"]>;
  id_ENDS_WITH?: InputMaybe<Scalars["ID"]["input"]>;
  id_NOT_CONTAINS?: InputMaybe<Scalars["ID"]["input"]>;
  id_NOT_STARTS_WITH?: InputMaybe<Scalars["ID"]["input"]>;
  id_NOT_ENDS_WITH?: InputMaybe<Scalars["ID"]["input"]>;
  name?: InputMaybe<Scalars["String"]["input"]>;
  name_NOT?: InputMaybe<Scalars["String"]["input"]>;
  name_IN?: InputMaybe<Array<Scalars["String"]["input"]>>;
  name_NOT_IN?: InputMaybe<Array<Scalars["String"]["input"]>>;
  name_CONTAINS?: InputMaybe<Scalars["String"]["input"]>;
  name_STARTS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  name_ENDS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  name_MATCHES?: InputMaybe<Scalars["String"]["input"]>;
  name_NOT_CONTAINS?: InputMaybe<Scalars["String"]["input"]>;
  name_NOT_STARTS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  name_NOT_ENDS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  bio?: InputMaybe<Scalars["String"]["input"]>;
  bio_NOT?: InputMaybe<Scalars["String"]["input"]>;
  bio_IN?: InputMaybe<Array<InputMaybe<Scalars["String"]["input"]>>>;
  bio_NOT_IN?: InputMaybe<Array<InputMaybe<Scalars["String"]["input"]>>>;
  bio_CONTAINS?: InputMaybe<Scalars["String"]["input"]>;
  bio_STARTS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  bio_ENDS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  bio_MATCHES?: InputMaybe<Scalars["String"]["input"]>;
  bio_NOT_CONTAINS?: InputMaybe<Scalars["String"]["input"]>;
  bio_NOT_STARTS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  bio_NOT_ENDS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  bornYear?: InputMaybe<Scalars["Int"]["input"]>;
  bornYear_NOT?: InputMaybe<Scalars["Int"]["input"]>;
  bornYear_IN?: InputMaybe<Array<InputMaybe<Scalars["Int"]["input"]>>>;
  bornYear_NOT_IN?: InputMaybe<Array<InputMaybe<Scalars["Int"]["input"]>>>;
  bornYear_LT?: InputMaybe<Scalars["Int"]["input"]>;
  bornYear_LTE?: InputMaybe<Scalars["Int"]["input"]>;
  bornYear_GT?: InputMaybe<Scalars["Int"]["input"]>;
  bornYear_GTE?: InputMaybe<Scalars["Int"]["input"]>;
  OR?: InputMaybe<Array<AuthorWhere>>;
  AND?: InputMaybe<Array<AuthorWhere>>;
  NOT?: InputMaybe<AuthorWhere>;
  mode?: "insensitive" | (string & {});
  booksAggregate?: InputMaybe<AuthorBooksAggregateInput>;
  books?: InputMaybe<BookWhere>;
  books_NOT?: InputMaybe<BookWhere>;
  booksConnection?: InputMaybe<AuthorBooksConnectionWhere>;
  booksConnection_NOT?: InputMaybe<AuthorBooksConnectionWhere>;
  books_ALL?: InputMaybe<BookWhere>;
  books_NONE?: InputMaybe<BookWhere>;
  books_SINGLE?: InputMaybe<BookWhere>;
  books_SOME?: InputMaybe<BookWhere>;
  booksConnection_ALL?: InputMaybe<AuthorBooksConnectionWhere>;
  booksConnection_NONE?: InputMaybe<AuthorBooksConnectionWhere>;
  booksConnection_SINGLE?: InputMaybe<AuthorBooksConnectionWhere>;
  booksConnection_SOME?: InputMaybe<AuthorBooksConnectionWhere>;
};

export type BookWhere = {
  id?: InputMaybe<Scalars["ID"]["input"]>;
  id_NOT?: InputMaybe<Scalars["ID"]["input"]>;
  id_IN?: InputMaybe<Array<Scalars["ID"]["input"]>>;
  id_NOT_IN?: InputMaybe<Array<Scalars["ID"]["input"]>>;
  id_CONTAINS?: InputMaybe<Scalars["ID"]["input"]>;
  id_STARTS_WITH?: InputMaybe<Scalars["ID"]["input"]>;
  id_ENDS_WITH?: InputMaybe<Scalars["ID"]["input"]>;
  id_NOT_CONTAINS?: InputMaybe<Scalars["ID"]["input"]>;
  id_NOT_STARTS_WITH?: InputMaybe<Scalars["ID"]["input"]>;
  id_NOT_ENDS_WITH?: InputMaybe<Scalars["ID"]["input"]>;
  title?: InputMaybe<Scalars["String"]["input"]>;
  title_NOT?: InputMaybe<Scalars["String"]["input"]>;
  title_IN?: InputMaybe<Array<Scalars["String"]["input"]>>;
  title_NOT_IN?: InputMaybe<Array<Scalars["String"]["input"]>>;
  title_CONTAINS?: InputMaybe<Scalars["String"]["input"]>;
  title_STARTS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  title_ENDS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  title_MATCHES?: InputMaybe<Scalars["String"]["input"]>;
  title_NOT_CONTAINS?: InputMaybe<Scalars["String"]["input"]>;
  title_NOT_STARTS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  title_NOT_ENDS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  isbn?: InputMaybe<Scalars["String"]["input"]>;
  isbn_NOT?: InputMaybe<Scalars["String"]["input"]>;
  isbn_IN?: InputMaybe<Array<InputMaybe<Scalars["String"]["input"]>>>;
  isbn_NOT_IN?: InputMaybe<Array<InputMaybe<Scalars["String"]["input"]>>>;
  isbn_CONTAINS?: InputMaybe<Scalars["String"]["input"]>;
  isbn_STARTS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  isbn_ENDS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  isbn_MATCHES?: InputMaybe<Scalars["String"]["input"]>;
  isbn_NOT_CONTAINS?: InputMaybe<Scalars["String"]["input"]>;
  isbn_NOT_STARTS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  isbn_NOT_ENDS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  description?: InputMaybe<Scalars["String"]["input"]>;
  description_NOT?: InputMaybe<Scalars["String"]["input"]>;
  description_IN?: InputMaybe<Array<InputMaybe<Scalars["String"]["input"]>>>;
  description_NOT_IN?: InputMaybe<
    Array<InputMaybe<Scalars["String"]["input"]>>
  >;
  description_CONTAINS?: InputMaybe<Scalars["String"]["input"]>;
  description_STARTS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  description_ENDS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  description_MATCHES?: InputMaybe<Scalars["String"]["input"]>;
  description_NOT_CONTAINS?: InputMaybe<Scalars["String"]["input"]>;
  description_NOT_STARTS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  description_NOT_ENDS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  price?: InputMaybe<Scalars["Float"]["input"]>;
  price_NOT?: InputMaybe<Scalars["Float"]["input"]>;
  price_IN?: InputMaybe<Array<InputMaybe<Scalars["Float"]["input"]>>>;
  price_NOT_IN?: InputMaybe<Array<InputMaybe<Scalars["Float"]["input"]>>>;
  price_LT?: InputMaybe<Scalars["Float"]["input"]>;
  price_LTE?: InputMaybe<Scalars["Float"]["input"]>;
  price_GT?: InputMaybe<Scalars["Float"]["input"]>;
  price_GTE?: InputMaybe<Scalars["Float"]["input"]>;
  published?: InputMaybe<Scalars["DateTime"]["input"]>;
  published_NOT?: InputMaybe<Scalars["DateTime"]["input"]>;
  published_IN?: InputMaybe<Array<InputMaybe<Scalars["DateTime"]["input"]>>>;
  published_NOT_IN?: InputMaybe<
    Array<InputMaybe<Scalars["DateTime"]["input"]>>
  >;
  published_LT?: InputMaybe<Scalars["DateTime"]["input"]>;
  published_LTE?: InputMaybe<Scalars["DateTime"]["input"]>;
  published_GT?: InputMaybe<Scalars["DateTime"]["input"]>;
  published_GTE?: InputMaybe<Scalars["DateTime"]["input"]>;
  status?: InputMaybe<BookStatus>;
  status_NOT?: InputMaybe<BookStatus>;
  status_IN?: InputMaybe<Array<InputMaybe<BookStatus>>>;
  status_NOT_IN?: InputMaybe<Array<InputMaybe<BookStatus>>>;
  OR?: InputMaybe<Array<BookWhere>>;
  AND?: InputMaybe<Array<BookWhere>>;
  NOT?: InputMaybe<BookWhere>;
  mode?: "insensitive" | (string & {});
  authorAggregate?: InputMaybe<BookAuthorAggregateInput>;
  author?: InputMaybe<AuthorWhere>;
  author_NOT?: InputMaybe<AuthorWhere>;
  authorConnection?: InputMaybe<BookAuthorConnectionWhere>;
  authorConnection_NOT?: InputMaybe<BookAuthorConnectionWhere>;
  categoriesAggregate?: InputMaybe<BookCategoriesAggregateInput>;
  categories?: InputMaybe<CategoryWhere>;
  categories_NOT?: InputMaybe<CategoryWhere>;
  categoriesConnection?: InputMaybe<BookCategoriesConnectionWhere>;
  categoriesConnection_NOT?: InputMaybe<BookCategoriesConnectionWhere>;
  categories_ALL?: InputMaybe<CategoryWhere>;
  categories_NONE?: InputMaybe<CategoryWhere>;
  categories_SINGLE?: InputMaybe<CategoryWhere>;
  categories_SOME?: InputMaybe<CategoryWhere>;
  categoriesConnection_ALL?: InputMaybe<BookCategoriesConnectionWhere>;
  categoriesConnection_NONE?: InputMaybe<BookCategoriesConnectionWhere>;
  categoriesConnection_SINGLE?: InputMaybe<BookCategoriesConnectionWhere>;
  categoriesConnection_SOME?: InputMaybe<BookCategoriesConnectionWhere>;
  reviewsAggregate?: InputMaybe<BookReviewsAggregateInput>;
  reviews?: InputMaybe<ReviewWhere>;
  reviews_NOT?: InputMaybe<ReviewWhere>;
  reviewsConnection?: InputMaybe<BookReviewsConnectionWhere>;
  reviewsConnection_NOT?: InputMaybe<BookReviewsConnectionWhere>;
  reviews_ALL?: InputMaybe<ReviewWhere>;
  reviews_NONE?: InputMaybe<ReviewWhere>;
  reviews_SINGLE?: InputMaybe<ReviewWhere>;
  reviews_SOME?: InputMaybe<ReviewWhere>;
  reviewsConnection_ALL?: InputMaybe<BookReviewsConnectionWhere>;
  reviewsConnection_NONE?: InputMaybe<BookReviewsConnectionWhere>;
  reviewsConnection_SINGLE?: InputMaybe<BookReviewsConnectionWhere>;
  reviewsConnection_SOME?: InputMaybe<BookReviewsConnectionWhere>;
};

export type CategoryWhere = {
  id?: InputMaybe<Scalars["ID"]["input"]>;
  id_NOT?: InputMaybe<Scalars["ID"]["input"]>;
  id_IN?: InputMaybe<Array<Scalars["ID"]["input"]>>;
  id_NOT_IN?: InputMaybe<Array<Scalars["ID"]["input"]>>;
  id_CONTAINS?: InputMaybe<Scalars["ID"]["input"]>;
  id_STARTS_WITH?: InputMaybe<Scalars["ID"]["input"]>;
  id_ENDS_WITH?: InputMaybe<Scalars["ID"]["input"]>;
  id_NOT_CONTAINS?: InputMaybe<Scalars["ID"]["input"]>;
  id_NOT_STARTS_WITH?: InputMaybe<Scalars["ID"]["input"]>;
  id_NOT_ENDS_WITH?: InputMaybe<Scalars["ID"]["input"]>;
  name?: InputMaybe<Scalars["String"]["input"]>;
  name_NOT?: InputMaybe<Scalars["String"]["input"]>;
  name_IN?: InputMaybe<Array<Scalars["String"]["input"]>>;
  name_NOT_IN?: InputMaybe<Array<Scalars["String"]["input"]>>;
  name_CONTAINS?: InputMaybe<Scalars["String"]["input"]>;
  name_STARTS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  name_ENDS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  name_MATCHES?: InputMaybe<Scalars["String"]["input"]>;
  name_NOT_CONTAINS?: InputMaybe<Scalars["String"]["input"]>;
  name_NOT_STARTS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  name_NOT_ENDS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  OR?: InputMaybe<Array<CategoryWhere>>;
  AND?: InputMaybe<Array<CategoryWhere>>;
  NOT?: InputMaybe<CategoryWhere>;
  mode?: "insensitive" | (string & {});
  booksAggregate?: InputMaybe<CategoryBooksAggregateInput>;
  books?: InputMaybe<BookWhere>;
  books_NOT?: InputMaybe<BookWhere>;
  booksConnection?: InputMaybe<CategoryBooksConnectionWhere>;
  booksConnection_NOT?: InputMaybe<CategoryBooksConnectionWhere>;
  books_ALL?: InputMaybe<BookWhere>;
  books_NONE?: InputMaybe<BookWhere>;
  books_SINGLE?: InputMaybe<BookWhere>;
  books_SOME?: InputMaybe<BookWhere>;
  booksConnection_ALL?: InputMaybe<CategoryBooksConnectionWhere>;
  booksConnection_NONE?: InputMaybe<CategoryBooksConnectionWhere>;
  booksConnection_SINGLE?: InputMaybe<CategoryBooksConnectionWhere>;
  booksConnection_SOME?: InputMaybe<CategoryBooksConnectionWhere>;
};

export type PublisherWhere = {
  id?: InputMaybe<Scalars["ID"]["input"]>;
  id_NOT?: InputMaybe<Scalars["ID"]["input"]>;
  id_IN?: InputMaybe<Array<Scalars["ID"]["input"]>>;
  id_NOT_IN?: InputMaybe<Array<Scalars["ID"]["input"]>>;
  id_CONTAINS?: InputMaybe<Scalars["ID"]["input"]>;
  id_STARTS_WITH?: InputMaybe<Scalars["ID"]["input"]>;
  id_ENDS_WITH?: InputMaybe<Scalars["ID"]["input"]>;
  id_NOT_CONTAINS?: InputMaybe<Scalars["ID"]["input"]>;
  id_NOT_STARTS_WITH?: InputMaybe<Scalars["ID"]["input"]>;
  id_NOT_ENDS_WITH?: InputMaybe<Scalars["ID"]["input"]>;
  name?: InputMaybe<Scalars["String"]["input"]>;
  name_NOT?: InputMaybe<Scalars["String"]["input"]>;
  name_IN?: InputMaybe<Array<Scalars["String"]["input"]>>;
  name_NOT_IN?: InputMaybe<Array<Scalars["String"]["input"]>>;
  name_CONTAINS?: InputMaybe<Scalars["String"]["input"]>;
  name_STARTS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  name_ENDS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  name_MATCHES?: InputMaybe<Scalars["String"]["input"]>;
  name_NOT_CONTAINS?: InputMaybe<Scalars["String"]["input"]>;
  name_NOT_STARTS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  name_NOT_ENDS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  website?: InputMaybe<Scalars["String"]["input"]>;
  website_NOT?: InputMaybe<Scalars["String"]["input"]>;
  website_IN?: InputMaybe<Array<InputMaybe<Scalars["String"]["input"]>>>;
  website_NOT_IN?: InputMaybe<Array<InputMaybe<Scalars["String"]["input"]>>>;
  website_CONTAINS?: InputMaybe<Scalars["String"]["input"]>;
  website_STARTS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  website_ENDS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  website_MATCHES?: InputMaybe<Scalars["String"]["input"]>;
  website_NOT_CONTAINS?: InputMaybe<Scalars["String"]["input"]>;
  website_NOT_STARTS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  website_NOT_ENDS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  OR?: InputMaybe<Array<PublisherWhere>>;
  AND?: InputMaybe<Array<PublisherWhere>>;
  NOT?: InputMaybe<PublisherWhere>;
  mode?: "insensitive" | (string & {});
};

export type ReviewWhere = {
  id?: InputMaybe<Scalars["ID"]["input"]>;
  id_NOT?: InputMaybe<Scalars["ID"]["input"]>;
  id_IN?: InputMaybe<Array<Scalars["ID"]["input"]>>;
  id_NOT_IN?: InputMaybe<Array<Scalars["ID"]["input"]>>;
  id_CONTAINS?: InputMaybe<Scalars["ID"]["input"]>;
  id_STARTS_WITH?: InputMaybe<Scalars["ID"]["input"]>;
  id_ENDS_WITH?: InputMaybe<Scalars["ID"]["input"]>;
  id_NOT_CONTAINS?: InputMaybe<Scalars["ID"]["input"]>;
  id_NOT_STARTS_WITH?: InputMaybe<Scalars["ID"]["input"]>;
  id_NOT_ENDS_WITH?: InputMaybe<Scalars["ID"]["input"]>;
  rating?: InputMaybe<Scalars["Int"]["input"]>;
  rating_NOT?: InputMaybe<Scalars["Int"]["input"]>;
  rating_IN?: InputMaybe<Array<Scalars["Int"]["input"]>>;
  rating_NOT_IN?: InputMaybe<Array<Scalars["Int"]["input"]>>;
  rating_LT?: InputMaybe<Scalars["Int"]["input"]>;
  rating_LTE?: InputMaybe<Scalars["Int"]["input"]>;
  rating_GT?: InputMaybe<Scalars["Int"]["input"]>;
  rating_GTE?: InputMaybe<Scalars["Int"]["input"]>;
  comment?: InputMaybe<Scalars["String"]["input"]>;
  comment_NOT?: InputMaybe<Scalars["String"]["input"]>;
  comment_IN?: InputMaybe<Array<InputMaybe<Scalars["String"]["input"]>>>;
  comment_NOT_IN?: InputMaybe<Array<InputMaybe<Scalars["String"]["input"]>>>;
  comment_CONTAINS?: InputMaybe<Scalars["String"]["input"]>;
  comment_STARTS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  comment_ENDS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  comment_MATCHES?: InputMaybe<Scalars["String"]["input"]>;
  comment_NOT_CONTAINS?: InputMaybe<Scalars["String"]["input"]>;
  comment_NOT_STARTS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  comment_NOT_ENDS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  OR?: InputMaybe<Array<ReviewWhere>>;
  AND?: InputMaybe<Array<ReviewWhere>>;
  NOT?: InputMaybe<ReviewWhere>;
  mode?: "insensitive" | (string & {});
  bookAggregate?: InputMaybe<ReviewBookAggregateInput>;
  book?: InputMaybe<BookWhere>;
  book_NOT?: InputMaybe<BookWhere>;
  bookConnection?: InputMaybe<ReviewBookConnectionWhere>;
  bookConnection_NOT?: InputMaybe<ReviewBookConnectionWhere>;
};

export type EntityWhere = {
  id?: InputMaybe<Scalars["ID"]["input"]>;
  id_NOT?: InputMaybe<Scalars["ID"]["input"]>;
  id_IN?: InputMaybe<Array<Scalars["ID"]["input"]>>;
  id_NOT_IN?: InputMaybe<Array<Scalars["ID"]["input"]>>;
  id_CONTAINS?: InputMaybe<Scalars["ID"]["input"]>;
  id_STARTS_WITH?: InputMaybe<Scalars["ID"]["input"]>;
  id_ENDS_WITH?: InputMaybe<Scalars["ID"]["input"]>;
  id_NOT_CONTAINS?: InputMaybe<Scalars["ID"]["input"]>;
  id_NOT_STARTS_WITH?: InputMaybe<Scalars["ID"]["input"]>;
  id_NOT_ENDS_WITH?: InputMaybe<Scalars["ID"]["input"]>;
  name?: InputMaybe<Scalars["String"]["input"]>;
  name_NOT?: InputMaybe<Scalars["String"]["input"]>;
  name_IN?: InputMaybe<Array<Scalars["String"]["input"]>>;
  name_NOT_IN?: InputMaybe<Array<Scalars["String"]["input"]>>;
  name_CONTAINS?: InputMaybe<Scalars["String"]["input"]>;
  name_STARTS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  name_ENDS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  name_MATCHES?: InputMaybe<Scalars["String"]["input"]>;
  name_NOT_CONTAINS?: InputMaybe<Scalars["String"]["input"]>;
  name_NOT_STARTS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  name_NOT_ENDS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  OR?: InputMaybe<Array<EntityWhere>>;
  AND?: InputMaybe<Array<EntityWhere>>;
  NOT?: InputMaybe<EntityWhere>;
  mode?: "insensitive" | (string & {});
};

export type InCategoryWhere = {
  addedAt?: InputMaybe<Scalars["DateTime"]["input"]>;
  addedAt_NOT?: InputMaybe<Scalars["DateTime"]["input"]>;
  addedAt_IN?: InputMaybe<Array<InputMaybe<Scalars["DateTime"]["input"]>>>;
  addedAt_NOT_IN?: InputMaybe<Array<InputMaybe<Scalars["DateTime"]["input"]>>>;
  addedAt_LT?: InputMaybe<Scalars["DateTime"]["input"]>;
  addedAt_LTE?: InputMaybe<Scalars["DateTime"]["input"]>;
  addedAt_GT?: InputMaybe<Scalars["DateTime"]["input"]>;
  addedAt_GTE?: InputMaybe<Scalars["DateTime"]["input"]>;
  isPrimary?: InputMaybe<Scalars["Boolean"]["input"]>;
  isPrimary_NOT?: InputMaybe<Scalars["Boolean"]["input"]>;
  OR?: InputMaybe<Array<InCategoryWhere>>;
  AND?: InputMaybe<Array<InCategoryWhere>>;
  NOT?: InputMaybe<InCategoryWhere>;
  mode?: "insensitive" | (string & {});
};

export type WrittenByWhere = {
  role?: InputMaybe<Scalars["String"]["input"]>;
  role_NOT?: InputMaybe<Scalars["String"]["input"]>;
  role_IN?: InputMaybe<Array<InputMaybe<Scalars["String"]["input"]>>>;
  role_NOT_IN?: InputMaybe<Array<InputMaybe<Scalars["String"]["input"]>>>;
  role_CONTAINS?: InputMaybe<Scalars["String"]["input"]>;
  role_STARTS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  role_ENDS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  role_MATCHES?: InputMaybe<Scalars["String"]["input"]>;
  role_NOT_CONTAINS?: InputMaybe<Scalars["String"]["input"]>;
  role_NOT_STARTS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  role_NOT_ENDS_WITH?: InputMaybe<Scalars["String"]["input"]>;
  year?: InputMaybe<Scalars["Int"]["input"]>;
  year_NOT?: InputMaybe<Scalars["Int"]["input"]>;
  year_IN?: InputMaybe<Array<InputMaybe<Scalars["Int"]["input"]>>>;
  year_NOT_IN?: InputMaybe<Array<InputMaybe<Scalars["Int"]["input"]>>>;
  year_LT?: InputMaybe<Scalars["Int"]["input"]>;
  year_LTE?: InputMaybe<Scalars["Int"]["input"]>;
  year_GT?: InputMaybe<Scalars["Int"]["input"]>;
  year_GTE?: InputMaybe<Scalars["Int"]["input"]>;
  OR?: InputMaybe<Array<WrittenByWhere>>;
  AND?: InputMaybe<Array<WrittenByWhere>>;
  NOT?: InputMaybe<WrittenByWhere>;
  mode?: "insensitive" | (string & {});
};

export type AuthorBooksConnectionWhere = {
  node?: InputMaybe<BookWhere>;
  node_NOT?: InputMaybe<BookWhere>;
  edge?: InputMaybe<WrittenByWhere>;
  edge_NOT?: InputMaybe<WrittenByWhere>;
  AND?: InputMaybe<Array<AuthorBooksConnectionWhere>>;
  OR?: InputMaybe<Array<AuthorBooksConnectionWhere>>;
  NOT?: InputMaybe<AuthorBooksConnectionWhere>;
};

export type BookAuthorConnectionWhere = {
  node?: InputMaybe<AuthorWhere>;
  node_NOT?: InputMaybe<AuthorWhere>;
  edge?: InputMaybe<WrittenByWhere>;
  edge_NOT?: InputMaybe<WrittenByWhere>;
  AND?: InputMaybe<Array<BookAuthorConnectionWhere>>;
  OR?: InputMaybe<Array<BookAuthorConnectionWhere>>;
  NOT?: InputMaybe<BookAuthorConnectionWhere>;
};

export type BookCategoriesConnectionWhere = {
  node?: InputMaybe<CategoryWhere>;
  node_NOT?: InputMaybe<CategoryWhere>;
  edge?: InputMaybe<InCategoryWhere>;
  edge_NOT?: InputMaybe<InCategoryWhere>;
  AND?: InputMaybe<Array<BookCategoriesConnectionWhere>>;
  OR?: InputMaybe<Array<BookCategoriesConnectionWhere>>;
  NOT?: InputMaybe<BookCategoriesConnectionWhere>;
};

export type BookReviewsConnectionWhere = {
  node?: InputMaybe<ReviewWhere>;
  node_NOT?: InputMaybe<ReviewWhere>;
  AND?: InputMaybe<Array<BookReviewsConnectionWhere>>;
  OR?: InputMaybe<Array<BookReviewsConnectionWhere>>;
  NOT?: InputMaybe<BookReviewsConnectionWhere>;
};

export type CategoryBooksConnectionWhere = {
  node?: InputMaybe<BookWhere>;
  node_NOT?: InputMaybe<BookWhere>;
  AND?: InputMaybe<Array<CategoryBooksConnectionWhere>>;
  OR?: InputMaybe<Array<CategoryBooksConnectionWhere>>;
  NOT?: InputMaybe<CategoryBooksConnectionWhere>;
};

export type ReviewBookConnectionWhere = {
  node?: InputMaybe<BookWhere>;
  node_NOT?: InputMaybe<BookWhere>;
  AND?: InputMaybe<Array<ReviewBookConnectionWhere>>;
  OR?: InputMaybe<Array<ReviewBookConnectionWhere>>;
  NOT?: InputMaybe<ReviewBookConnectionWhere>;
};

export type AuthorCreateInput = {
  name: Scalars["String"]["input"];
  bio?: InputMaybe<Scalars["String"]["input"]>;
  bornYear?: InputMaybe<Scalars["Int"]["input"]>;
  books?: InputMaybe<AuthorBooksFieldInput>;
};

export type AuthorUpdateInput = {
  name?: InputMaybe<Scalars["String"]["input"]>;
  bio?: InputMaybe<Scalars["String"]["input"]>;
  bornYear?: InputMaybe<Scalars["Int"]["input"]>;
  books?: InputMaybe<Array<AuthorBooksUpdateFieldInput>>;
};

export type AuthorConnectInput = {
  books?: InputMaybe<Array<AuthorBooksConnectFieldInput>>;
};

export type AuthorDisconnectInput = {
  books?: InputMaybe<Array<AuthorBooksDisconnectFieldInput>>;
};

export type AuthorDeleteInput = {
  books?: InputMaybe<Array<AuthorBooksDeleteFieldInput>>;
};

export type AuthorBooksFieldInput = {
  connect?: InputMaybe<Array<AuthorBooksConnectFieldInput>>;
  create?: InputMaybe<Array<AuthorBooksCreateFieldInput>>;
};

export type AuthorBooksCreateFieldInput = {
  edge?: InputMaybe<WrittenByCreateInput>;
  node: BookCreateInput;
};

export type AuthorBooksConnectFieldInput = {
  edge?: InputMaybe<WrittenByCreateInput>;
  where?: InputMaybe<BookConnectWhere>;
  /** Whether or not to overwrite any matching relationship with the new properties. */
  overwrite?: Scalars["Boolean"]["input"];
  connect?: InputMaybe<Array<BookConnectInput>>;
};

export type AuthorBooksDisconnectFieldInput = {
  where?: InputMaybe<AuthorBooksConnectionWhere>;
  disconnect?: InputMaybe<BookDisconnectInput>;
};

export type AuthorBooksDeleteFieldInput = {
  where?: InputMaybe<AuthorBooksConnectionWhere>;
  delete?: InputMaybe<BookDeleteInput>;
};

export type AuthorBooksUpdateFieldInput = {
  where?: InputMaybe<AuthorBooksConnectionWhere>;
  connect?: InputMaybe<Array<AuthorBooksConnectFieldInput>>;
  disconnect?: InputMaybe<Array<AuthorBooksDisconnectFieldInput>>;
  create?: InputMaybe<Array<AuthorBooksCreateFieldInput>>;
  update?: InputMaybe<AuthorBooksUpdateConnectionInput>;
  delete?: InputMaybe<Array<AuthorBooksDeleteFieldInput>>;
};

export type AuthorBooksUpdateConnectionInput = {
  node?: InputMaybe<BookUpdateInput>;
  edge?: InputMaybe<WrittenByUpdateInput>;
};

export type BookConnectWhere = {
  node: BookWhere;
};

export type BookCreateInput = {
  title: Scalars["String"]["input"];
  isbn?: InputMaybe<Scalars["String"]["input"]>;
  description?: InputMaybe<Scalars["String"]["input"]>;
  price?: InputMaybe<Scalars["Float"]["input"]>;
  published?: InputMaybe<Scalars["DateTime"]["input"]>;
  status?: InputMaybe<BookStatus>;
  author?: InputMaybe<BookAuthorFieldInput>;
  categories?: InputMaybe<BookCategoriesFieldInput>;
  reviews?: InputMaybe<BookReviewsFieldInput>;
};

export type BookUpdateInput = {
  title?: InputMaybe<Scalars["String"]["input"]>;
  isbn?: InputMaybe<Scalars["String"]["input"]>;
  description?: InputMaybe<Scalars["String"]["input"]>;
  price?: InputMaybe<Scalars["Float"]["input"]>;
  published?: InputMaybe<Scalars["DateTime"]["input"]>;
  status?: InputMaybe<BookStatus>;
  author?: InputMaybe<BookAuthorUpdateFieldInput>;
  categories?: InputMaybe<Array<BookCategoriesUpdateFieldInput>>;
  reviews?: InputMaybe<Array<BookReviewsUpdateFieldInput>>;
};

export type BookConnectInput = {
  author?: InputMaybe<BookAuthorConnectFieldInput>;
  categories?: InputMaybe<Array<BookCategoriesConnectFieldInput>>;
  reviews?: InputMaybe<Array<BookReviewsConnectFieldInput>>;
};

export type BookDisconnectInput = {
  author?: InputMaybe<BookAuthorDisconnectFieldInput>;
  categories?: InputMaybe<Array<BookCategoriesDisconnectFieldInput>>;
  reviews?: InputMaybe<Array<BookReviewsDisconnectFieldInput>>;
};

export type BookDeleteInput = {
  author?: InputMaybe<BookAuthorDeleteFieldInput>;
  categories?: InputMaybe<Array<BookCategoriesDeleteFieldInput>>;
  reviews?: InputMaybe<Array<BookReviewsDeleteFieldInput>>;
};

export type BookAuthorFieldInput = {
  connect?: InputMaybe<BookAuthorConnectFieldInput>;
  create?: InputMaybe<BookAuthorCreateFieldInput>;
};

export type BookAuthorCreateFieldInput = {
  edge?: InputMaybe<WrittenByCreateInput>;
  node: AuthorCreateInput;
};

export type BookAuthorConnectFieldInput = {
  edge?: InputMaybe<WrittenByCreateInput>;
  where?: InputMaybe<AuthorConnectWhere>;
  /** Whether or not to overwrite any matching relationship with the new properties. */
  overwrite?: Scalars["Boolean"]["input"];
  connect?: InputMaybe<AuthorConnectInput>;
};

export type BookAuthorDisconnectFieldInput = {
  where?: InputMaybe<BookAuthorConnectionWhere>;
  disconnect?: InputMaybe<AuthorDisconnectInput>;
};

export type BookAuthorDeleteFieldInput = {
  where?: InputMaybe<BookAuthorConnectionWhere>;
  delete?: InputMaybe<AuthorDeleteInput>;
};

export type BookAuthorUpdateFieldInput = {
  where?: InputMaybe<BookAuthorConnectionWhere>;
  connect?: InputMaybe<BookAuthorConnectFieldInput>;
  disconnect?: InputMaybe<BookAuthorDisconnectFieldInput>;
  create?: InputMaybe<BookAuthorCreateFieldInput>;
  update?: InputMaybe<BookAuthorUpdateConnectionInput>;
  delete?: InputMaybe<BookAuthorDeleteFieldInput>;
};

export type BookAuthorUpdateConnectionInput = {
  node?: InputMaybe<AuthorUpdateInput>;
  edge?: InputMaybe<WrittenByUpdateInput>;
};

export type AuthorConnectWhere = {
  node: AuthorWhere;
};

export type BookCategoriesFieldInput = {
  connect?: InputMaybe<Array<BookCategoriesConnectFieldInput>>;
  create?: InputMaybe<Array<BookCategoriesCreateFieldInput>>;
};

export type BookCategoriesCreateFieldInput = {
  edge?: InputMaybe<InCategoryCreateInput>;
  node: CategoryCreateInput;
};

export type BookCategoriesConnectFieldInput = {
  edge?: InputMaybe<InCategoryCreateInput>;
  where?: InputMaybe<CategoryConnectWhere>;
  /** Whether or not to overwrite any matching relationship with the new properties. */
  overwrite?: Scalars["Boolean"]["input"];
  connect?: InputMaybe<Array<CategoryConnectInput>>;
};

export type BookCategoriesDisconnectFieldInput = {
  where?: InputMaybe<BookCategoriesConnectionWhere>;
  disconnect?: InputMaybe<CategoryDisconnectInput>;
};

export type BookCategoriesDeleteFieldInput = {
  where?: InputMaybe<BookCategoriesConnectionWhere>;
  delete?: InputMaybe<CategoryDeleteInput>;
};

export type BookCategoriesUpdateFieldInput = {
  where?: InputMaybe<BookCategoriesConnectionWhere>;
  connect?: InputMaybe<Array<BookCategoriesConnectFieldInput>>;
  disconnect?: InputMaybe<Array<BookCategoriesDisconnectFieldInput>>;
  create?: InputMaybe<Array<BookCategoriesCreateFieldInput>>;
  update?: InputMaybe<BookCategoriesUpdateConnectionInput>;
  delete?: InputMaybe<Array<BookCategoriesDeleteFieldInput>>;
};

export type BookCategoriesUpdateConnectionInput = {
  node?: InputMaybe<CategoryUpdateInput>;
  edge?: InputMaybe<InCategoryUpdateInput>;
};

export type CategoryConnectWhere = {
  node: CategoryWhere;
};

export type BookReviewsFieldInput = {
  connect?: InputMaybe<Array<BookReviewsConnectFieldInput>>;
  create?: InputMaybe<Array<BookReviewsCreateFieldInput>>;
};

export type BookReviewsCreateFieldInput = {
  node: ReviewCreateInput;
};

export type BookReviewsConnectFieldInput = {
  where?: InputMaybe<ReviewConnectWhere>;
  /** Whether or not to overwrite any matching relationship with the new properties. */
  overwrite?: Scalars["Boolean"]["input"];
  connect?: InputMaybe<Array<ReviewConnectInput>>;
};

export type BookReviewsDisconnectFieldInput = {
  where?: InputMaybe<BookReviewsConnectionWhere>;
  disconnect?: InputMaybe<ReviewDisconnectInput>;
};

export type BookReviewsDeleteFieldInput = {
  where?: InputMaybe<BookReviewsConnectionWhere>;
  delete?: InputMaybe<ReviewDeleteInput>;
};

export type BookReviewsUpdateFieldInput = {
  where?: InputMaybe<BookReviewsConnectionWhere>;
  connect?: InputMaybe<Array<BookReviewsConnectFieldInput>>;
  disconnect?: InputMaybe<Array<BookReviewsDisconnectFieldInput>>;
  create?: InputMaybe<Array<BookReviewsCreateFieldInput>>;
  update?: InputMaybe<BookReviewsUpdateConnectionInput>;
  delete?: InputMaybe<Array<BookReviewsDeleteFieldInput>>;
};

export type BookReviewsUpdateConnectionInput = {
  node?: InputMaybe<ReviewUpdateInput>;
};

export type ReviewConnectWhere = {
  node: ReviewWhere;
};

export type CategoryCreateInput = {
  name: Scalars["String"]["input"];
  books?: InputMaybe<CategoryBooksFieldInput>;
};

export type CategoryUpdateInput = {
  name?: InputMaybe<Scalars["String"]["input"]>;
  books?: InputMaybe<Array<CategoryBooksUpdateFieldInput>>;
};

export type CategoryConnectInput = {
  books?: InputMaybe<Array<CategoryBooksConnectFieldInput>>;
};

export type CategoryDisconnectInput = {
  books?: InputMaybe<Array<CategoryBooksDisconnectFieldInput>>;
};

export type CategoryDeleteInput = {
  books?: InputMaybe<Array<CategoryBooksDeleteFieldInput>>;
};

export type CategoryBooksFieldInput = {
  connect?: InputMaybe<Array<CategoryBooksConnectFieldInput>>;
  create?: InputMaybe<Array<CategoryBooksCreateFieldInput>>;
};

export type CategoryBooksCreateFieldInput = {
  node: BookCreateInput;
};

export type CategoryBooksConnectFieldInput = {
  where?: InputMaybe<BookConnectWhere>;
  /** Whether or not to overwrite any matching relationship with the new properties. */
  overwrite?: Scalars["Boolean"]["input"];
  connect?: InputMaybe<Array<BookConnectInput>>;
};

export type CategoryBooksDisconnectFieldInput = {
  where?: InputMaybe<CategoryBooksConnectionWhere>;
  disconnect?: InputMaybe<BookDisconnectInput>;
};

export type CategoryBooksDeleteFieldInput = {
  where?: InputMaybe<CategoryBooksConnectionWhere>;
  delete?: InputMaybe<BookDeleteInput>;
};

export type CategoryBooksUpdateFieldInput = {
  where?: InputMaybe<CategoryBooksConnectionWhere>;
  connect?: InputMaybe<Array<CategoryBooksConnectFieldInput>>;
  disconnect?: InputMaybe<Array<CategoryBooksDisconnectFieldInput>>;
  create?: InputMaybe<Array<CategoryBooksCreateFieldInput>>;
  update?: InputMaybe<CategoryBooksUpdateConnectionInput>;
  delete?: InputMaybe<Array<CategoryBooksDeleteFieldInput>>;
};

export type CategoryBooksUpdateConnectionInput = {
  node?: InputMaybe<BookUpdateInput>;
};

export type PublisherCreateInput = {
  name: Scalars["String"]["input"];
  website?: InputMaybe<Scalars["String"]["input"]>;
};

export type PublisherUpdateInput = {
  name?: InputMaybe<Scalars["String"]["input"]>;
  website?: InputMaybe<Scalars["String"]["input"]>;
};

export type ReviewCreateInput = {
  rating: Scalars["Int"]["input"];
  comment?: InputMaybe<Scalars["String"]["input"]>;
  book?: InputMaybe<ReviewBookFieldInput>;
};

export type ReviewUpdateInput = {
  rating?: InputMaybe<Scalars["Int"]["input"]>;
  comment?: InputMaybe<Scalars["String"]["input"]>;
  book?: InputMaybe<ReviewBookUpdateFieldInput>;
};

export type ReviewConnectInput = {
  book?: InputMaybe<ReviewBookConnectFieldInput>;
};

export type ReviewDisconnectInput = {
  book?: InputMaybe<ReviewBookDisconnectFieldInput>;
};

export type ReviewDeleteInput = {
  book?: InputMaybe<ReviewBookDeleteFieldInput>;
};

export type ReviewBookFieldInput = {
  connect?: InputMaybe<ReviewBookConnectFieldInput>;
  create?: InputMaybe<ReviewBookCreateFieldInput>;
};

export type ReviewBookCreateFieldInput = {
  node: BookCreateInput;
};

export type ReviewBookConnectFieldInput = {
  where?: InputMaybe<BookConnectWhere>;
  /** Whether or not to overwrite any matching relationship with the new properties. */
  overwrite?: Scalars["Boolean"]["input"];
  connect?: InputMaybe<BookConnectInput>;
};

export type ReviewBookDisconnectFieldInput = {
  where?: InputMaybe<ReviewBookConnectionWhere>;
  disconnect?: InputMaybe<BookDisconnectInput>;
};

export type ReviewBookDeleteFieldInput = {
  where?: InputMaybe<ReviewBookConnectionWhere>;
  delete?: InputMaybe<BookDeleteInput>;
};

export type ReviewBookUpdateFieldInput = {
  where?: InputMaybe<ReviewBookConnectionWhere>;
  connect?: InputMaybe<ReviewBookConnectFieldInput>;
  disconnect?: InputMaybe<ReviewBookDisconnectFieldInput>;
  create?: InputMaybe<ReviewBookCreateFieldInput>;
  update?: InputMaybe<ReviewBookUpdateConnectionInput>;
  delete?: InputMaybe<ReviewBookDeleteFieldInput>;
};

export type ReviewBookUpdateConnectionInput = {
  node?: InputMaybe<BookUpdateInput>;
};

export type InCategoryCreateInput = {
  addedAt?: InputMaybe<Scalars["DateTime"]["input"]>;
  isPrimary?: InputMaybe<Scalars["Boolean"]["input"]>;
};

export type InCategoryUpdateInput = {
  addedAt?: InputMaybe<Scalars["DateTime"]["input"]>;
  isPrimary?: InputMaybe<Scalars["Boolean"]["input"]>;
};

export type WrittenByCreateInput = {
  role?: InputMaybe<Scalars["String"]["input"]>;
  year?: InputMaybe<Scalars["Int"]["input"]>;
};

export type WrittenByUpdateInput = {
  role?: InputMaybe<Scalars["String"]["input"]>;
  year?: InputMaybe<Scalars["Int"]["input"]>;
};

export type EntityCreateInput = {
  Author?: InputMaybe<AuthorCreateInput>;
  Publisher?: InputMaybe<PublisherCreateInput>;
};

export type EntityUpdateInput = {
  Author?: InputMaybe<AuthorUpdateInput>;
  Publisher?: InputMaybe<PublisherUpdateInput>;
};

export type EntityConnectInput = {
  Author?: InputMaybe<Array<AuthorConnectInput>>;
};

export type EntityDisconnectInput = {
  Author?: InputMaybe<Array<AuthorDisconnectInput>>;
};

export type EntityDeleteInput = {
  Author?: InputMaybe<Array<AuthorDeleteInput>>;
};

export type AuthorSort = {
  id?: InputMaybe<SortDirection>;
  name?: InputMaybe<SortDirection>;
  bio?: InputMaybe<SortDirection>;
  bornYear?: InputMaybe<SortDirection>;
};

export type AuthorOptions = {
  limit?: InputMaybe<Scalars["Int"]["input"]>;
  offset?: InputMaybe<Scalars["Int"]["input"]>;
  sort?: InputMaybe<Array<AuthorSort>>;
};

export type BookSort = {
  id?: InputMaybe<SortDirection>;
  title?: InputMaybe<SortDirection>;
  isbn?: InputMaybe<SortDirection>;
  description?: InputMaybe<SortDirection>;
  price?: InputMaybe<SortDirection>;
  published?: InputMaybe<SortDirection>;
  status?: InputMaybe<SortDirection>;
};

export type BookOptions = {
  limit?: InputMaybe<Scalars["Int"]["input"]>;
  offset?: InputMaybe<Scalars["Int"]["input"]>;
  sort?: InputMaybe<Array<BookSort>>;
};

export type CategorySort = {
  id?: InputMaybe<SortDirection>;
  name?: InputMaybe<SortDirection>;
};

export type CategoryOptions = {
  limit?: InputMaybe<Scalars["Int"]["input"]>;
  offset?: InputMaybe<Scalars["Int"]["input"]>;
  sort?: InputMaybe<Array<CategorySort>>;
};

export type PublisherSort = {
  id?: InputMaybe<SortDirection>;
  name?: InputMaybe<SortDirection>;
  website?: InputMaybe<SortDirection>;
};

export type PublisherOptions = {
  limit?: InputMaybe<Scalars["Int"]["input"]>;
  offset?: InputMaybe<Scalars["Int"]["input"]>;
  sort?: InputMaybe<Array<PublisherSort>>;
};

export type ReviewSort = {
  id?: InputMaybe<SortDirection>;
  rating?: InputMaybe<SortDirection>;
  comment?: InputMaybe<SortDirection>;
};

export type ReviewOptions = {
  limit?: InputMaybe<Scalars["Int"]["input"]>;
  offset?: InputMaybe<Scalars["Int"]["input"]>;
  sort?: InputMaybe<Array<ReviewSort>>;
};

export type EntitySort = {
  id?: InputMaybe<SortDirection>;
  name?: InputMaybe<SortDirection>;
};

export type EntityOptions = {
  limit?: InputMaybe<Scalars["Int"]["input"]>;
  offset?: InputMaybe<Scalars["Int"]["input"]>;
  sort?: InputMaybe<Array<EntitySort>>;
};

export type PageInfo = {
  hasNextPage: Scalars["Boolean"]["output"];
  hasPreviousPage: Scalars["Boolean"]["output"];
  startCursor?: Maybe<Scalars["String"]["output"]>;
  endCursor?: Maybe<Scalars["String"]["output"]>;
};

export type AuthorBooksConnection = {
  edges: Array<AuthorBooksRelationship>;
  totalCount: Scalars["Int"]["output"];
  pageInfo: PageInfo;
};

export type AuthorBooksRelationship = {
  cursor: Scalars["String"]["output"];
  node: Book;
  properties: WrittenBy;
};

export type BookAuthorConnection = {
  edges: Array<BookAuthorRelationship>;
  totalCount: Scalars["Int"]["output"];
  pageInfo: PageInfo;
};

export type BookAuthorRelationship = {
  cursor: Scalars["String"]["output"];
  node: Author;
  properties: WrittenBy;
};

export type BookCategoriesConnection = {
  edges: Array<BookCategoriesRelationship>;
  totalCount: Scalars["Int"]["output"];
  pageInfo: PageInfo;
};

export type BookCategoriesRelationship = {
  cursor: Scalars["String"]["output"];
  node: Category;
  properties: InCategory;
};

export type BookReviewsConnection = {
  edges: Array<BookReviewsRelationship>;
  totalCount: Scalars["Int"]["output"];
  pageInfo: PageInfo;
};

export type BookReviewsRelationship = {
  cursor: Scalars["String"]["output"];
  node: Review;
};

export type CategoryBooksConnection = {
  edges: Array<CategoryBooksRelationship>;
  totalCount: Scalars["Int"]["output"];
  pageInfo: PageInfo;
};

export type CategoryBooksRelationship = {
  cursor: Scalars["String"]["output"];
  node: Book;
};

export type ReviewBookConnection = {
  edges: Array<ReviewBookRelationship>;
  totalCount: Scalars["Int"]["output"];
  pageInfo: PageInfo;
};

export type ReviewBookRelationship = {
  cursor: Scalars["String"]["output"];
  node: Book;
};

export type IdAggregateSelection = {
  __typename?: "IDAggregateSelection";
  shortest?: Maybe<Scalars["ID"]["output"]>;
  longest?: Maybe<Scalars["ID"]["output"]>;
};

export type StringAggregateSelection = {
  __typename?: "StringAggregateSelection";
  shortest?: Maybe<Scalars["String"]["output"]>;
  longest?: Maybe<Scalars["String"]["output"]>;
};

export type IntAggregateSelection = {
  __typename?: "IntAggregateSelection";
  max?: Maybe<Scalars["Int"]["output"]>;
  min?: Maybe<Scalars["Int"]["output"]>;
  average?: Maybe<Scalars["Float"]["output"]>;
  sum?: Maybe<Scalars["Int"]["output"]>;
};

export type FloatAggregateSelection = {
  __typename?: "FloatAggregateSelection";
  max?: Maybe<Scalars["Float"]["output"]>;
  min?: Maybe<Scalars["Float"]["output"]>;
  average?: Maybe<Scalars["Float"]["output"]>;
  sum?: Maybe<Scalars["Float"]["output"]>;
};

export type DateTimeAggregateSelection = {
  __typename?: "DateTimeAggregateSelection";
  min?: Maybe<Scalars["DateTime"]["output"]>;
  max?: Maybe<Scalars["DateTime"]["output"]>;
};

export type AuthorAggregateSelection = {
  __typename?: "AuthorAggregateSelection";
  count: Scalars["Int"]["output"];
  id: IdAggregateSelection;
  name: StringAggregateSelection;
  bio: StringAggregateSelection;
  bornYear: IntAggregateSelection;
};

export type AuthorBookBooksAggregationSelection = {
  __typename?: "AuthorBookBooksAggregationSelection";
  count: Scalars["Int"]["output"];
  node?: Maybe<AuthorBookBooksNodeAggregateSelection>;
  edge?: Maybe<AuthorBookBooksEdgeAggregateSelection>;
};

export type AuthorBookBooksNodeAggregateSelection = {
  __typename?: "AuthorBookBooksNodeAggregateSelection";
  id: IdAggregateSelection;
  title: StringAggregateSelection;
  isbn: StringAggregateSelection;
  description: StringAggregateSelection;
  price: FloatAggregateSelection;
  published: DateTimeAggregateSelection;
};

export type AuthorBookBooksEdgeAggregateSelection = {
  __typename?: "AuthorBookBooksEdgeAggregateSelection";
  role: StringAggregateSelection;
  year: IntAggregateSelection;
};

export type AuthorBooksAggregateInput = {
  count?: InputMaybe<Scalars["Int"]["input"]>;
  count_LT?: InputMaybe<Scalars["Int"]["input"]>;
  count_LTE?: InputMaybe<Scalars["Int"]["input"]>;
  count_GT?: InputMaybe<Scalars["Int"]["input"]>;
  count_GTE?: InputMaybe<Scalars["Int"]["input"]>;
  AND?: InputMaybe<Array<AuthorBooksAggregateInput>>;
  OR?: InputMaybe<Array<AuthorBooksAggregateInput>>;
  NOT?: InputMaybe<AuthorBooksAggregateInput>;
};

export type BookAggregateSelection = {
  __typename?: "BookAggregateSelection";
  count: Scalars["Int"]["output"];
  id: IdAggregateSelection;
  title: StringAggregateSelection;
  isbn: StringAggregateSelection;
  description: StringAggregateSelection;
  price: FloatAggregateSelection;
  published: DateTimeAggregateSelection;
};

export type BookAuthorAuthorAggregationSelection = {
  __typename?: "BookAuthorAuthorAggregationSelection";
  count: Scalars["Int"]["output"];
  node?: Maybe<BookAuthorAuthorNodeAggregateSelection>;
  edge?: Maybe<BookAuthorAuthorEdgeAggregateSelection>;
};

export type BookAuthorAuthorNodeAggregateSelection = {
  __typename?: "BookAuthorAuthorNodeAggregateSelection";
  id: IdAggregateSelection;
  name: StringAggregateSelection;
  bio: StringAggregateSelection;
  bornYear: IntAggregateSelection;
};

export type BookAuthorAuthorEdgeAggregateSelection = {
  __typename?: "BookAuthorAuthorEdgeAggregateSelection";
  role: StringAggregateSelection;
  year: IntAggregateSelection;
};

export type BookAuthorAggregateInput = {
  count?: InputMaybe<Scalars["Int"]["input"]>;
  count_LT?: InputMaybe<Scalars["Int"]["input"]>;
  count_LTE?: InputMaybe<Scalars["Int"]["input"]>;
  count_GT?: InputMaybe<Scalars["Int"]["input"]>;
  count_GTE?: InputMaybe<Scalars["Int"]["input"]>;
  AND?: InputMaybe<Array<BookAuthorAggregateInput>>;
  OR?: InputMaybe<Array<BookAuthorAggregateInput>>;
  NOT?: InputMaybe<BookAuthorAggregateInput>;
};

export type BookCategoryCategoriesAggregationSelection = {
  __typename?: "BookCategoryCategoriesAggregationSelection";
  count: Scalars["Int"]["output"];
  node?: Maybe<BookCategoryCategoriesNodeAggregateSelection>;
  edge?: Maybe<BookCategoryCategoriesEdgeAggregateSelection>;
};

export type BookCategoryCategoriesNodeAggregateSelection = {
  __typename?: "BookCategoryCategoriesNodeAggregateSelection";
  id: IdAggregateSelection;
  name: StringAggregateSelection;
};

export type BookCategoryCategoriesEdgeAggregateSelection = {
  __typename?: "BookCategoryCategoriesEdgeAggregateSelection";
  addedAt: DateTimeAggregateSelection;
};

export type BookCategoriesAggregateInput = {
  count?: InputMaybe<Scalars["Int"]["input"]>;
  count_LT?: InputMaybe<Scalars["Int"]["input"]>;
  count_LTE?: InputMaybe<Scalars["Int"]["input"]>;
  count_GT?: InputMaybe<Scalars["Int"]["input"]>;
  count_GTE?: InputMaybe<Scalars["Int"]["input"]>;
  AND?: InputMaybe<Array<BookCategoriesAggregateInput>>;
  OR?: InputMaybe<Array<BookCategoriesAggregateInput>>;
  NOT?: InputMaybe<BookCategoriesAggregateInput>;
};

export type BookReviewReviewsAggregationSelection = {
  __typename?: "BookReviewReviewsAggregationSelection";
  count: Scalars["Int"]["output"];
  node?: Maybe<BookReviewReviewsNodeAggregateSelection>;
};

export type BookReviewReviewsNodeAggregateSelection = {
  __typename?: "BookReviewReviewsNodeAggregateSelection";
  id: IdAggregateSelection;
  rating: IntAggregateSelection;
  comment: StringAggregateSelection;
};

export type BookReviewsAggregateInput = {
  count?: InputMaybe<Scalars["Int"]["input"]>;
  count_LT?: InputMaybe<Scalars["Int"]["input"]>;
  count_LTE?: InputMaybe<Scalars["Int"]["input"]>;
  count_GT?: InputMaybe<Scalars["Int"]["input"]>;
  count_GTE?: InputMaybe<Scalars["Int"]["input"]>;
  AND?: InputMaybe<Array<BookReviewsAggregateInput>>;
  OR?: InputMaybe<Array<BookReviewsAggregateInput>>;
  NOT?: InputMaybe<BookReviewsAggregateInput>;
};

export type CategoryAggregateSelection = {
  __typename?: "CategoryAggregateSelection";
  count: Scalars["Int"]["output"];
  id: IdAggregateSelection;
  name: StringAggregateSelection;
};

export type CategoryBookBooksAggregationSelection = {
  __typename?: "CategoryBookBooksAggregationSelection";
  count: Scalars["Int"]["output"];
  node?: Maybe<CategoryBookBooksNodeAggregateSelection>;
};

export type CategoryBookBooksNodeAggregateSelection = {
  __typename?: "CategoryBookBooksNodeAggregateSelection";
  id: IdAggregateSelection;
  title: StringAggregateSelection;
  isbn: StringAggregateSelection;
  description: StringAggregateSelection;
  price: FloatAggregateSelection;
  published: DateTimeAggregateSelection;
};

export type CategoryBooksAggregateInput = {
  count?: InputMaybe<Scalars["Int"]["input"]>;
  count_LT?: InputMaybe<Scalars["Int"]["input"]>;
  count_LTE?: InputMaybe<Scalars["Int"]["input"]>;
  count_GT?: InputMaybe<Scalars["Int"]["input"]>;
  count_GTE?: InputMaybe<Scalars["Int"]["input"]>;
  AND?: InputMaybe<Array<CategoryBooksAggregateInput>>;
  OR?: InputMaybe<Array<CategoryBooksAggregateInput>>;
  NOT?: InputMaybe<CategoryBooksAggregateInput>;
};

export type PublisherAggregateSelection = {
  __typename?: "PublisherAggregateSelection";
  count: Scalars["Int"]["output"];
  id: IdAggregateSelection;
  name: StringAggregateSelection;
  website: StringAggregateSelection;
};

export type ReviewAggregateSelection = {
  __typename?: "ReviewAggregateSelection";
  count: Scalars["Int"]["output"];
  id: IdAggregateSelection;
  rating: IntAggregateSelection;
  comment: StringAggregateSelection;
};

export type ReviewBookBookAggregationSelection = {
  __typename?: "ReviewBookBookAggregationSelection";
  count: Scalars["Int"]["output"];
  node?: Maybe<ReviewBookBookNodeAggregateSelection>;
};

export type ReviewBookBookNodeAggregateSelection = {
  __typename?: "ReviewBookBookNodeAggregateSelection";
  id: IdAggregateSelection;
  title: StringAggregateSelection;
  isbn: StringAggregateSelection;
  description: StringAggregateSelection;
  price: FloatAggregateSelection;
  published: DateTimeAggregateSelection;
};

export type ReviewBookAggregateInput = {
  count?: InputMaybe<Scalars["Int"]["input"]>;
  count_LT?: InputMaybe<Scalars["Int"]["input"]>;
  count_LTE?: InputMaybe<Scalars["Int"]["input"]>;
  count_GT?: InputMaybe<Scalars["Int"]["input"]>;
  count_GTE?: InputMaybe<Scalars["Int"]["input"]>;
  AND?: InputMaybe<Array<ReviewBookAggregateInput>>;
  OR?: InputMaybe<Array<ReviewBookAggregateInput>>;
  NOT?: InputMaybe<ReviewBookAggregateInput>;
};

export type CreateInfo = {
  nodesCreated: Scalars["Int"]["output"];
  nodesDeleted?: Scalars["Int"]["output"];
  relationshipsCreated: Scalars["Int"]["output"];
  relationshipsDeleted?: Scalars["Int"]["output"];
};

export type UpdateInfo = {
  nodesCreated: Scalars["Int"]["output"];
  nodesDeleted?: Scalars["Int"]["output"];
  relationshipsCreated: Scalars["Int"]["output"];
  relationshipsDeleted?: Scalars["Int"]["output"];
};

export type MutationInfoSelectFields = {
  nodesCreated?: boolean;
  nodesDeleted?: boolean;
  relationshipsCreated?: boolean;
  relationshipsDeleted?: boolean;
};

export type CreateAuthorsMutationResponse = {
  info: CreateInfo;
  authors: Array<Author>;
};

export type UpdateAuthorsMutationResponse = {
  info: UpdateInfo;
  authors: Array<Author>;
};

export type AuthorMutationSelectFields = {
  info?: MutationInfoSelectFields;
  authors?: AuthorSelectFields;
};

export type CreateBooksMutationResponse = {
  info: CreateInfo;
  books: Array<Book>;
};

export type UpdateBooksMutationResponse = {
  info: UpdateInfo;
  books: Array<Book>;
};

export type BookMutationSelectFields = {
  info?: MutationInfoSelectFields;
  books?: BookSelectFields;
};

export type CreateCategoriesMutationResponse = {
  info: CreateInfo;
  categories: Array<Category>;
};

export type UpdateCategoriesMutationResponse = {
  info: UpdateInfo;
  categories: Array<Category>;
};

export type CategoryMutationSelectFields = {
  info?: MutationInfoSelectFields;
  categories?: CategorySelectFields;
};

export type CreatePublishersMutationResponse = {
  info: CreateInfo;
  publishers: Array<Publisher>;
};

export type UpdatePublishersMutationResponse = {
  info: UpdateInfo;
  publishers: Array<Publisher>;
};

export type PublisherMutationSelectFields = {
  info?: MutationInfoSelectFields;
  publishers?: PublisherSelectFields;
};

export type CreateReviewsMutationResponse = {
  info: CreateInfo;
  reviews: Array<Review>;
};

export type UpdateReviewsMutationResponse = {
  info: UpdateInfo;
  reviews: Array<Review>;
};

export type ReviewMutationSelectFields = {
  info?: MutationInfoSelectFields;
  reviews?: ReviewSelectFields;
};

export type FloatWhere = {
  min?: InputMaybe<Scalars["Float"]["input"]>;
  max?: InputMaybe<Scalars["Float"]["input"]>;
};

export type FulltextIndexEntry = {
  phrase: string;
  score?: number;
};

export type BookFulltextResult = {
  __typename?: "BookFulltextResult";
  score: Scalars["Float"]["output"];
  book: Book;
};

/** The input for filtering a fulltext query on an index of Book */
export type BookFulltextWhere = {
  score?: InputMaybe<FloatWhere>;
  book?: InputMaybe<BookWhere>;
};

export type BookFulltextSort = {
  score?: InputMaybe<SortDirection>;
  book?: InputMaybe<BookSort>;
};

export type BookFulltextLeaf = {
  BookSearch?: FulltextIndexEntry;
};

export type BookFulltextInput =
  | BookFulltextLeaf
  | { OR: BookFulltextInput[] }
  | { AND: BookFulltextInput[] }
  | { NOT: BookFulltextInput };

export type AuthorBooksEdgeSelectFields = {
  role?: boolean;
  year?: boolean;
};

export type BookAuthorEdgeSelectFields = {
  role?: boolean;
  year?: boolean;
};

export type BookCategoriesEdgeSelectFields = {
  addedAt?: boolean;
  isPrimary?: boolean;
};

export type AuthorSelectFields = {
  id?: boolean;
  name?: boolean;
  bio?: boolean;
  bornYear?: boolean;
  books?:
    | boolean
    | {
        where?: BookWhere;
        select?: BookSelectFields;
        orderBy?: Array<Record<string, "ASC" | "DESC">>;
      };
  booksConnection?:
    | boolean
    | {
        where?: AuthorBooksConnectionWhere;
        orderBy?: Array<
          | { node: Record<string, "ASC" | "DESC"> }
          | { edge: Record<string, "ASC" | "DESC"> }
        >;
        select: {
          edges?:
            | boolean
            | {
                node?: boolean | { select: BookSelectFields };
                properties?: boolean | { select: AuthorBooksEdgeSelectFields };
              };
        };
      };
};

export type BookSelectFields = {
  id?: boolean;
  title?: boolean;
  isbn?: boolean;
  description?: boolean;
  price?: boolean;
  published?: boolean;
  status?: boolean;
  author?: boolean | { where?: AuthorWhere; select?: AuthorSelectFields };
  categories?:
    | boolean
    | {
        where?: CategoryWhere;
        select?: CategorySelectFields;
        orderBy?: Array<Record<string, "ASC" | "DESC">>;
      };
  reviews?:
    | boolean
    | {
        where?: ReviewWhere;
        select?: ReviewSelectFields;
        orderBy?: Array<Record<string, "ASC" | "DESC">>;
      };
  authorConnection?:
    | boolean
    | {
        where?: BookAuthorConnectionWhere;
        orderBy?: Array<
          | { node: Record<string, "ASC" | "DESC"> }
          | { edge: Record<string, "ASC" | "DESC"> }
        >;
        select: {
          edges?:
            | boolean
            | {
                node?: boolean | { select: AuthorSelectFields };
                properties?: boolean | { select: BookAuthorEdgeSelectFields };
              };
        };
      };
  categoriesConnection?:
    | boolean
    | {
        where?: BookCategoriesConnectionWhere;
        orderBy?: Array<
          | { node: Record<string, "ASC" | "DESC"> }
          | { edge: Record<string, "ASC" | "DESC"> }
        >;
        select: {
          edges?:
            | boolean
            | {
                node?: boolean | { select: CategorySelectFields };
                properties?:
                  | boolean
                  | { select: BookCategoriesEdgeSelectFields };
              };
        };
      };
  reviewsConnection?:
    | boolean
    | {
        where?: BookReviewsConnectionWhere;
        orderBy?: Array<{ node: Record<string, "ASC" | "DESC"> }>;
        select: {
          edges?:
            | boolean
            | {
                node?: boolean | { select: ReviewSelectFields };
              };
        };
      };
};

export type CategorySelectFields = {
  id?: boolean;
  name?: boolean;
  books?:
    | boolean
    | {
        where?: BookWhere;
        select?: BookSelectFields;
        orderBy?: Array<Record<string, "ASC" | "DESC">>;
      };
  booksConnection?:
    | boolean
    | {
        where?: CategoryBooksConnectionWhere;
        orderBy?: Array<{ node: Record<string, "ASC" | "DESC"> }>;
        select: {
          edges?:
            | boolean
            | {
                node?: boolean | { select: BookSelectFields };
              };
        };
      };
};

export type PublisherSelectFields = {
  id?: boolean;
  name?: boolean;
  website?: boolean;
};

export type ReviewSelectFields = {
  id?: boolean;
  rating?: boolean;
  comment?: boolean;
  book?: boolean | { where?: BookWhere; select?: BookSelectFields };
  bookConnection?:
    | boolean
    | {
        where?: ReviewBookConnectionWhere;
        orderBy?: Array<{ node: Record<string, "ASC" | "DESC"> }>;
        select: {
          edges?:
            | boolean
            | {
                node?: boolean | { select: BookSelectFields };
              };
        };
      };
};

export type EntitySelectFields = {
  id?: boolean;
  name?: boolean;
};

export type SelectFields = Record<
  string,
  boolean | { select: SelectFields } | { where?: unknown; select: unknown }
>;

export type SelectResult<T, S extends SelectFields> = {
  [K in keyof S & keyof T]: S[K] extends true
    ? T[K]
    : S[K] extends { select: infer NestedS }
      ? T[K] extends Array<infer U>
        ? NestedS extends SelectFields
          ? Array<SelectResult<U, NestedS>>
          : T[K]
        : T[K] extends infer U | null | undefined
          ? NestedS extends SelectFields
            ? SelectResult<NonNullable<U>, NestedS> | null
            : T[K]
          : T[K]
      : never;
};

type MutationInfoFields = {
  nodesCreated: number;
  nodesDeleted: number;
  relationshipsCreated: number;
  relationshipsDeleted: number;
};

export type MutationInfoResult<S extends Record<string, boolean>> = {
  [K in keyof S & keyof MutationInfoFields]: MutationInfoFields[K];
};

export type MutationSelectResult<
  T,
  TPluralKey extends string,
  S extends Record<string, unknown>,
> = ("info" extends keyof S
  ? S["info"] extends Record<string, boolean>
    ? { info: MutationInfoResult<S["info"]> }
    : {}
  : {}) &
  (TPluralKey extends keyof S
    ? S[TPluralKey] extends SelectFields
      ? {
          [K in TPluralKey]: Array<
            SelectResult<T, S[TPluralKey] & SelectFields>
          >;
        }
      : {}
    : {});

export type AuthorModel = ModelInterface<
  Author,
  AuthorSelectFields,
  AuthorWhere,
  AuthorCreateInput,
  AuthorUpdateInput,
  AuthorConnectInput,
  AuthorDisconnectInput,
  AuthorDeleteInput,
  "authors",
  AuthorMutationSelectFields,
  AuthorSort
>;

export type BookModel = ModelInterface<
  Book,
  BookSelectFields,
  BookWhere,
  BookCreateInput,
  BookUpdateInput,
  BookConnectInput,
  BookDisconnectInput,
  BookDeleteInput,
  "books",
  BookMutationSelectFields,
  BookSort,
  BookFulltextInput
>;

export type CategoryModel = ModelInterface<
  Category,
  CategorySelectFields,
  CategoryWhere,
  CategoryCreateInput,
  CategoryUpdateInput,
  CategoryConnectInput,
  CategoryDisconnectInput,
  CategoryDeleteInput,
  "categories",
  CategoryMutationSelectFields,
  CategorySort
>;

export type PublisherModel = ModelInterface<
  Publisher,
  PublisherSelectFields,
  PublisherWhere,
  PublisherCreateInput,
  PublisherUpdateInput,
  Record<string, never>,
  Record<string, never>,
  Record<string, never>,
  "publishers",
  PublisherMutationSelectFields,
  PublisherSort
>;

export type ReviewModel = ModelInterface<
  Review,
  ReviewSelectFields,
  ReviewWhere,
  ReviewCreateInput,
  ReviewUpdateInput,
  ReviewConnectInput,
  ReviewDisconnectInput,
  ReviewDeleteInput,
  "reviews",
  ReviewMutationSelectFields,
  ReviewSort
>;

export type EntityModel = InterfaceModelInterface<
  Entity,
  EntityWhere,
  EntitySort
>;

export type ModelMap = {
  Author: {
    Type: Author;
    SelectFields: AuthorSelectFields;
    MutationSelectFields: AuthorMutationSelectFields;
    Where: AuthorWhere;
    CreateInput: AuthorCreateInput;
    UpdateInput: AuthorUpdateInput;
    ConnectInput: AuthorConnectInput;
    DisconnectInput: AuthorDisconnectInput;
    DeleteInput: AuthorDeleteInput;
    PluralKey: "authors";
    Sort: AuthorSort;
  };
  Book: {
    Type: Book;
    SelectFields: BookSelectFields;
    MutationSelectFields: BookMutationSelectFields;
    Where: BookWhere;
    CreateInput: BookCreateInput;
    UpdateInput: BookUpdateInput;
    ConnectInput: BookConnectInput;
    DisconnectInput: BookDisconnectInput;
    DeleteInput: BookDeleteInput;
    PluralKey: "books";
    Sort: BookSort;
    Fulltext: BookFulltextInput;
  };
  Category: {
    Type: Category;
    SelectFields: CategorySelectFields;
    MutationSelectFields: CategoryMutationSelectFields;
    Where: CategoryWhere;
    CreateInput: CategoryCreateInput;
    UpdateInput: CategoryUpdateInput;
    ConnectInput: CategoryConnectInput;
    DisconnectInput: CategoryDisconnectInput;
    DeleteInput: CategoryDeleteInput;
    PluralKey: "categories";
    Sort: CategorySort;
  };
  Publisher: {
    Type: Publisher;
    SelectFields: PublisherSelectFields;
    MutationSelectFields: PublisherMutationSelectFields;
    Where: PublisherWhere;
    CreateInput: PublisherCreateInput;
    UpdateInput: PublisherUpdateInput;
    ConnectInput: Record<string, never>;
    DisconnectInput: Record<string, never>;
    DeleteInput: Record<string, never>;
    PluralKey: "publishers";
    Sort: PublisherSort;
  };
  Review: {
    Type: Review;
    SelectFields: ReviewSelectFields;
    MutationSelectFields: ReviewMutationSelectFields;
    Where: ReviewWhere;
    CreateInput: ReviewCreateInput;
    UpdateInput: ReviewUpdateInput;
    ConnectInput: ReviewConnectInput;
    DisconnectInput: ReviewDisconnectInput;
    DeleteInput: ReviewDeleteInput;
    PluralKey: "reviews";
    Sort: ReviewSort;
  };
  Entity: {
    Type: Entity;
    SelectFields: EntitySelectFields;
    Where: EntityWhere;
    CreateInput: Record<string, never>;
    UpdateInput: Record<string, never>;
    ConnectInput: Record<string, never>;
    DisconnectInput: Record<string, never>;
    DeleteInput: Record<string, never>;
    PluralKey: never;
    Sort: EntitySort;
  };
};

export type InterfaceModelMap = {
  Entity: {
    Type: Entity;
    Where: EntityWhere;
    Sort: EntitySort;
  };
};
